homework1
DjonniStorm/2024-2-VK-EDU-Frontend-I-Pazushkin pull request #1
Opened 2024-09-18 17:30 UTC by DjonniStorm

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.

Что было сделано:
* Задача с неуникальными элементами
* Задача с байтами и тесты к ней
* Задача с предложением

2024-09-19 11:55 UTC, nelkor requested changes
Одна небольшая правка, в остальном всё очень хорошо)

2024-09-19 11:55 UTC, nelkor commented on homework1/correctSentence.js
> +export function correctSentence(text) {
Вообще было бы неплохо тут тоже проверить аргумент на то, что он является строкой. И как обработаешь пустую строку? Или строку из одной буквы.

И на такие случае также было бы неплохо добавить тестов.

2024-09-20 08:20 UTC, nelkor approved these changes

2024-09-21 17:19 UTC, martinkomitsky approved these changes
12!

2024-09-21 17:19 UTC, merged